### PR TITLE
Styling changes

### PR DESCRIPTION
**Pull request by DarkStar1997**
Changed the code styles and have put a space between each operator and operator to adhere to Google's convention.

### CODE REVIEW

**Comment by dasayan05** [comment]
**Don't** changes folder structure like this. Don't put READMEs everywhere. Revert all README files. That's not a place for READMEs.

**Comment by dasayan05** [comment]
Don't do anything more on this PR. I will merge it now.

**Comment by DarkStar1997** [comment]
OK!!!

**Comment by dasayan05** [comment]
Merged ! :1st_place_medal:

**Comment by dasayan05** [comment]
@DarkStar1997 **Tips:** whenever you have to change/modify/revert commits *in a PR*, just reset them locally and then do a `force push` with new commits. Although it is advised *not to change public history* but as long as the PR is not merged, there is not harm in it.

**Pull request merged**
