### PR TITLE
Splitting and tokenizing operations support

### PR DESCRIPTION
**Pull request by DarkStar1997**

### CODE REVIEW

**Comment by dasayan05** [comment]
@DarkStar1997 I have made organizational and structural changes. Have a look.

Unless you tell `CMake` to allow using the headers, it won't be taken into consideration which was the case until I did [this commit](https://github.com/crystalcpp/practice/pull/1/commits/412396dc9aee0c9b8fee75e208a1b3d1e5fc1392)

I am yet to make actual code changes.

**Comment by dasayan05** [comment]
@DarkStar1997 may I ask you to do some coding style changes. I could have done that but let's see if you can do it at this point.

> Put `spaces` in proper places. your code has serious lack of `spaces` in them :-1: like `if(y==0)` should be `if (y == 0)` OR `T y=x<0?-x:x;` should be `T y = (x < 0) ? -x : x`. This is standard google coding principles. Do it throughout your code.

Please pull this PR (#1) at this point (with my changes) into your local and make the change and push it on top of this PR itself.

**Comment by DarkStar1997** [comment]
Ok. I will do it tomorrow.

**Comment by dasayan05** [comment]
Good.
1. Do the style improvements for `spliter.hpp` as well.
2. Add some test code for all the functions and classes you made (in `basic.cpp` for now, we will implement unit testings afterwards.

**Comment by dasayan05** [comment]
Tips: In [this commit](https://github.com/crystalcpp/practice/pull/1/commits/9c9d9d8f81c908f52534c64734719904c33da847), the message says that it adds *unary operator* but you also did some style improvements in it (which you apparently forgot to do in the previous one. For such cases `git commit` gives you an amazing option (`--amend` switch) which can make life easier ([read here](https://nathanhoad.net/git-amend-your-last-commit))

**Comment by dasayan05** [comment]
This PR moved to #2

**Pull request closed without merging**
